# Generated by Django 4.2.13 on 2024-06-22 14:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name_zone', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('coords_polys', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
    ]